# Generated by Django 3.0 on 2023-08-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fechaCreacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='codigo_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=250)),
                ('fechaCreacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='nuevo_usado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_uso', models.CharField(max_length=50)),
            ],
        ),
    ]
