# Generated by Django 3.0 on 2023-08-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_clientes_ingresosretiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresofacturas',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingresosretiros',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='precioSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacion', models.CharField(blank=True, max_length=70, null=True)),
                ('idEstatusUso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.nuevo_usado')),
                ('idcodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.codigo_prod')),
            ],
        ),
    ]
