# Generated by Django 3.0 on 2023-08-15 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_tipodecimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0006_cierreinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='salidaVentasContado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_venta', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('idBodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('idEstatusUso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.nuevo_usado')),
                ('id_empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
                ('id_estadoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.estadoPago')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clientes')),
                ('idcodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.codigo_prod')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.precioSalida')),
            ],
        ),
    ]
