# Generated by Django 3.0 on 2023-08-20 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0004_tipodecimo'),
        ('inventario', '0007_salidaventascontado'),
    ]

    operations = [
        migrations.CreateModel(
            name='movimimientosInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observacion', models.CharField(blank=True, max_length=150, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idBodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada_inventario', to='inventario.bodega')),
                ('idBodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida_inventario', to='inventario.bodega')),
                ('idEstatusUso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.nuevo_usado')),
                ('id_empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
                ('idcodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.codigo_prod')),
            ],
        ),
    ]
