# Generated by Django 3.0 on 2023-08-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_codigo_prod_seguimientoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='afnet', max_length=60),
        ),
    ]
