# Generated by Django 3.0 on 2023-08-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_clientes_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresofacturas',
            name='precio_factura',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingresofacturas',
            name='precio_in',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
