# Generated by Django 3.0 on 2023-09-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20230910_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierreinventario',
            name='ingreso_proveedores',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='ingreso_retiros',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='movimientos_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='movimientos_salida',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='salida_dañados',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='salida_instalaciones',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='salida_ventaContado',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='salida_ventaCredito',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ingresofacturas',
            name='precio_factura',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingresofacturas',
            name='precio_in',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='movimimientosinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='preciosalida',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='salidainstalaciones',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='salidaventascontado',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
