# Generated by Django 3.0 on 2023-05-22 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturasProveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFactura', models.CharField(max_length=100)),
                ('fechafactura', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechapago', models.DateField(blank=True)),
                ('estadoEntrega', models.BooleanField()),
                ('fechaentrega', models.DateField(blank=True)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cajasReg')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
                ('id_estadoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.estadoPago')),
                ('id_modoCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.modoCompra')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.proveedoresProd')),
            ],
        ),
    ]
