# Generated by Django 3.0 on 2023-05-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasproveedores',
            name='fechaentrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturasproveedores',
            name='fechapago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
