# Generated by Django 3.0 on 2023-05-22 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_empresaservicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egresos', '0005_decimos'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagoServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('creado', models.DateField(auto_now_add=True)),
                ('anio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pagoAnio')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cajasReg')),
                ('empresa_nuestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
                ('empresa_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.empresaServicio')),
                ('mes_de_Pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pagoMeses')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.serviciosMensuales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
