# Generated by Django 3.0 on 2023-05-22 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0003_institucionfinanciera'),
        ('egresos', '0006_pagoservicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagoCreditos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('anio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pagoAnio')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cajasReg')),
                ('mes_de_Pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pagoMeses')),
                ('nombre_coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.institucionFinanciera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
