# Generated by Django 3.0 on 2023-05-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_institucionfinanciera'),
        ('egresos', '0007_pagocreditos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocolaboradores',
            name='id_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.empresa'),
        ),
    ]
