# Generated by Django 3.0 on 2023-05-23 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_institucionfinanciera'),
        ('egresos', '0008_pagocolaboradores_id_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='decimos',
            name='id_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.empresa'),
        ),
        migrations.AddField(
            model_name='pagocreditos',
            name='id_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.empresa'),
        ),
        migrations.AddField(
            model_name='planillasiess',
            name='id_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.empresa'),
        ),
    ]
