# Generated by Django 3.0 on 2023-06-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_tipodecimo'),
        ('egresos', '0009_auto_20230523_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='decimos',
            name='id_tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='general.tipoDecimo'),
        ),
    ]
