# Generated by Django 3.0 on 2023-08-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_tipodecimo'),
        ('egresos', '0010_decimos_id_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('anio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pagoAnio')),
                ('id_empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
                ('mes_de_Pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pagoMeses')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cajasReg')),
            ],
        ),
    ]
