# Generated by Django 3.0 on 2023-09-16 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0011_socios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocolaboradores',
            name='estadoPagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagocolaboradores',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagocolaboradores',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
