# Generated by Django 3.0 on 2023-09-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0012_auto_20230916_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagocolaboradores',
            old_name='fecha_registro',
            new_name='fecha_ingreso',
        ),
    ]
