# Generated by Django 3.0 on 2023-05-22 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0003_institucionfinanciera'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresosCajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorIngreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('creado', models.DateField(auto_now_add=True)),
                ('conceptoIngreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ingresosConcepto')),
                ('empresaIngreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
                ('nombreCaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cajasReg')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
