# Generated by Django 3.0 on 2023-05-22 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0003_institucionfinanciera'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierresCajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valorIngresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorEgresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorMovSalida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorMovEntrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorCierreAnterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorCierreActual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado', models.DateField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cajasReg')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
