# Generated by Django 3.0 on 2023-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_empresaservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='institucionFinanciera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_finan', models.CharField(max_length=200)),
            ],
        ),
    ]
