# Generated by Django 3.0 on 2023-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_institucionfinanciera'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoDecimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=200)),
            ],
        ),
    ]
