# Generated by Django 3.0 on 2023-08-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_tipodecimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedoresprod',
            name='seguimientoFacturas',
            field=models.BooleanField(default=True),
        ),
    ]
