# Generated by Django 3.0 on 2023-05-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0003_institucionfinanciera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=250)),
                ('creado', models.DateField(auto_now_add=True)),
                ('caja_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='general.cajasReg')),
                ('caja_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='general.cajasReg')),
                ('empresaCaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
